In [1]:
import torch

## Tensor shape and dim

In [15]:
t = torch.zeros(6)
print(t)
print(t.dim()) # How many dimensions does my tensor have? / rank of my tensor

tensor([0., 0., 0., 0., 0., 0.])
1


In [17]:
t = torch.zeros(2,3) #standart vector notation, [y,x]
print(t)
print(t.dim())
print(t.shape)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
2
torch.Size([2, 3])


In [13]:
t = torch.zeros(2,5,6)
print(t)
print(t.dim())

tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])
3


#### Reading timeseries shape:

(34944, 96) :

We have 34,944 windows, each containing 96 timesteps/items.

## Retrieving data with index numbers